# **Homework 3**
Name: Maddox Guthrie \
Id: 12184185

## 1.1 Exercise 1: Column Replacement and Determinants (Cramer’s Rule Style)

### 1.1.1 Replace the i-th column of a matrix
Given a square matrix $A$ of size $n \times n$, a vector $v$ of size $n$ and an index $i$, where $0 \leq i \leq n - 1$.
Write a function that replaces the $i$-th column of $A$ with $v$ and returns a new matrix.

In [23]:
import numpy as np
from sympy.integrals.risch import frac_in


def replace_column(A, v, i):
    cpy = A.copy().astype(float)
    cpy[:, i] = v
    return cpy

### 1.1.2 Test cases

In [24]:
n = 4

A = np.random.randint(low=-5, high=5, size=(n, n))
v = np.random.normal(loc=0, scale=2, size=n)

for i in range(n):
    A_i = replace_column(A, v, i)
    print(A_i)

[[-2.95717325  2.          4.         -3.        ]
 [-1.65018956  0.         -1.         -5.        ]
 [-1.67393275 -5.         -3.          3.        ]
 [ 4.09817079  0.          0.         -5.        ]]
[[ 2.         -2.95717325  4.         -3.        ]
 [ 1.         -1.65018956 -1.         -5.        ]
 [-5.         -1.67393275 -3.          3.        ]
 [ 2.          4.09817079  0.         -5.        ]]
[[ 2.          2.         -2.95717325 -3.        ]
 [ 1.          0.         -1.65018956 -5.        ]
 [-5.         -5.         -1.67393275  3.        ]
 [ 2.          0.          4.09817079 -5.        ]]
[[ 2.          2.          4.         -2.95717325]
 [ 1.          0.         -1.         -1.65018956]
 [-5.         -5.         -3.         -1.67393275]
 [ 2.          0.          0.          4.09817079]]


### 1.1.3 Cramer’s Rule for Solving a System of Equations
Write a Python function that uses Cramer’s Rule to solve the system $Ax = b$. The function
should take $A$ and $b$ as inputs and return the solution vector $x$.

In [25]:
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])

b = np.array([4, 5, 6])

In [26]:
def cramer_solver(A, b):
    A_det = np.linalg.det(A)
    x = []
    for i in range(A.shape[0]):
        A_i = replace_column(A, b, i)
        A_i_det = np.linalg.det(A_i)
        x.append(A_i_det / A_det)
    return x

x1 = cramer_solver(A, b)
print(x1)

[np.float64(6.0), np.float64(14.999999999999993), np.float64(-23.0)]


Use the NumPy solver np.linalg.solve() to solve the same system.

In [27]:
x2 = np.linalg.solve(A, b)
print(x2)

[  6.  15. -23.]


Compare the two solutions to verify that your implementation of Cramer’s Rule is correct.

In [28]:
print(np.isclose(x1, x2))

[ True  True  True]


## 1.2 Exercise 2: Classifying Fruit — From Similarity to a Neural Network

### 1.2.1 Classify the New Fruit Using Cosine Similarity

In [29]:
apple1 = np.array([0.78, 0.50, 0.88, 0.65])
apple2 = np.array([0.79, 0.39, 0.90, 0.69])

banana1 = np.array([0.08, 0.94, 0.82, 0.78])
banana2 = np.array([0.07, 0.96, 0.79, 0.80])

orange1 = np.array([0.15, 0.47, 0.48, 0.91])
orange2 = np.array([0.10, 0.41, 0.40, 0.98])

new_fruit = np.array([0.05, 0.93, 0.79, 0.82])

**Write a Python function that computes the cosine similarity between two vectors**

In [30]:
def cosine_similarity(u,v):
    u_v_dot = np.dot(u,v)
    u_norm = np.linalg.norm(u)
    v_norm = np.linalg.norm(v)
    cos_sim = u_v_dot / (u_norm * v_norm)
    return cos_sim

**Use your function to compute the cosine similarity between the new fruit**

In [31]:
results = []
for fruit in fruits.values():
    results.append(cosine_similarity(fruit, new_fruit))

print(f"Cosine Similarity of new fruit vs each other fruit:")
for i, fruit in enumerate(fruits.keys()):
    print(f"{fruit}: {results[i]}")

most_similar_fruit = list(fruits)[results.index(max(results))]

print(f"\nThe new fruit is a {most_similar_fruit[:-2]} because it has the highest cosine similarity")

Cosine Similarity of new fruit vs each other fruit:
apple 1: 0.8213756609884086
apple 2: 0.7947969315916223
banana 1: 0.999193828247798
banana 2: 0.9996283906419465
orange 1: 0.9353889721593739
orange 2: 0.8983727348814866

The new fruit is a banana because it has the highest cosine similarity


Cosine similarity measures how close the direction of two vectors is. A score closer to 1 means the vectors point in similar directions. Therefore, becasue banana and the new fruit had the highest score (closer to 1) the new fruit is most likely a banana.

### 1.2.2 Build a Fruit Classifier

In [32]:
def fruit_classifier(new_fruit):
    fruits = {"apple 1": apple1, "apple 2": apple2, "banana 1": banana1, "banana 2": banana2, "orange 1": orange1, "orange 2": orange2}
    results = []

    for fruit in fruits.values():
        results.append(cosine_similarity(fruit, new_fruit))

    most_similar_fruit = (list(fruits)[results.index(max(results))])[:-2]
    return most_similar_fruit

print(fruit_classifier(new_fruit))

banana


### 1.2.3 A Basic Neural Network

In [33]:
fruit_vectors = np.array([
    [0.78, 0.5, 0.88, 0.65],
    [0.79, 0.39, 0.9, 0.69],
    [0.08, 0.94, 0.82, 0.78],
    [0.07, 0.96, 0.79, 0.8],
    [0.15, 0.47, 0.48, 0.91],
    [0.1, 0.41, 0.4, 0.98]
])

W1 = np.array(
    [
        [-4.91, -0.09, 0.31],
        [6.06, -0.28, 0.17],
        [2.21, 0.45, -0.36],
        [-0.90, -0.33, 0.01],
    ]
)

W2 = np.array(
    [
        [-7.04, 3.99, 1.16],
        [-0.36, -0.27, -0.16],
        [0.21, 0.52, -0.07],
    ]
)

b1 = np.array([-0.55, -0.03, -0.01])
b2 = np.array([7.13, -8.65, 1.52])

classes = ["apple", "banana", "orange"]

Write a function that takes a fruit vector 𝑋 as input and performs all the computations:
$XW1 + b1 \to ReLU \to HW2 + b2 \to softmax$

In [37]:
def relu(x):
    return np.maximum(0, x)

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

def fruit_nn_classifier(X, W1, W2, b1, b2, classes):
    y1 = np.dot(X, W1) + b1
    H = relu(y1)
    y2 = np.dot(H, W2) + b2
    prob = softmax(y2)
    max_idx = np.argmax(prob)
    return classes[max_idx]

In [38]:
for fruit in fruit_vectors:
    pred_name = fruit_classifier(fruit)
    print(f"Predicted: {pred_name} for {fruit}")


Predicted: apple for [0.78 0.5  0.88 0.65]
Predicted: apple for [0.79 0.39 0.9  0.69]
Predicted: banana for [0.08 0.94 0.82 0.78]
Predicted: banana for [0.07 0.96 0.79 0.8 ]
Predicted: orange for [0.15 0.47 0.48 0.91]
Predicted: orange for [0.1  0.41 0.4  0.98]


In [39]:
pred_name = fruit_nn_classifier(new_fruit, W1, W2, b1, b2, classes)
print(pred_name)

banana
