# Linear Algebra with Numpy (Python)

In [2]:
# install numpy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

## Vectors

- Vector is a list of numbers or 1-D array in Numpy.
- Use vectors to represent: a feature column of a dataset; the gradient to descend the loss function

In [4]:
# create vectors in Numpy
x = np.array([0.5, 1.2, 3.5, 7.3])

In [5]:
print(x)

[0.5 1.2 3.5 7.3]


**Notice:** `x` is a object in Numpy.

In [6]:
# check the type of the vector
print(type(x))

<class 'numpy.ndarray'>


For any `Numpy` array, we have some properties: `x.shape` (shape of the array) or `x.ndim` (dimensions) and `x.dtype` (data type)

In [7]:
print(x.shape)

(4,)


In [8]:
print(x.ndim)

1


In [9]:
print(x.dtype)

float64


In [10]:
x = np.array([0.5, 1.2, 3.5, 7.3])
y = np.array([0.2, 1.4, 2.2, 2.1])

In [11]:
len(x) == len(y)

True

In [13]:
# linear combination of vectors
z = 2*x + 3*y
print(z)

[ 1.6  6.6 13.6 20.9]


**Elementwise product:**

If $x = (x_1,x_2,\ldots,x_n)$ and $y = (y_1,y_2,\ldots,y_n)$ then
$$
x*y = (x_1y_1, x_2y_2, \ldots, x_ny_n).
$$

In [14]:
# what is x * y?
print(x*y)

[ 0.1   1.68  7.7  15.33]


**Dot Product:**
If $x = (x_1,x_2,\ldots,x_n)$ and $y = (y_1,y_2,\ldots,y_n)$ then
$$
x \dot y = x_1y_1 + x_2y_2+\cdots+x_ny_n.
$$

In [15]:
# compute the dot product
np.dot(x,y) == np.sum(x*y)

np.True_

In [16]:
x @ y

np.float64(24.810000000000002)

## Norm (len) of vectors
A norm of a vector is defined as
$$
\|x\|_{p} = (|x_1|^p+|x_2|^p+\cdots+|x_n|^p)^{1/p}
$$
In Numpy, we only need for $p=1$, $p=2$ or $p=\infty$

In [17]:
# compute the norm of vector
v = np.array([3.0, -4.0, 0])

In [18]:
l1_norm = np.linalg.norm(v, 1)
print(l1_norm)

7.0


In [21]:
linf_norm = np.linalg.norm(v, np.inf)
print(linf_norm)

4.0


In [23]:
# 12 norm
l2_norm = np.linalg.norm(v, 2)
print(l2_norm)

5.0


In [24]:
l2_norm = np.linalg.norm(v)
print(l2_norm)

5.0


**Example:** Write a function to compute the cosine similarity of two vectors.
If $x = (x_1,\ldots,x_n)$ and $y = (y_1,\ldots,y_n)$ then
$$
\cos(\theta) = \frac{x\cdot y}{\|x\|\|y\|}.
$$

In [31]:
def cos_sim(x, y):
    return (x @ y) / (np.linalg.norm(x) * np.linalg.norm(y))

In [32]:
# make up vectors
cat = np.array([0.9, 0.1, 0.0])
dog = np.array([0.85, 0.2, 0.0])
car = np.array([0.0, 0.1, 0.9])

In [33]:
# check the similarity between cat and dog
cos_sim(cat, dog)

np.float64(0.9927566538132715)

In [34]:
cos_sim(cat, car)

np.float64(0.012195121951219513)

## Matrices

Matrix is just a 2-D array in Numpy (or a list of lists). Use matrices for
- dataset (rows and columns)
- weight of layers in a DL model
- a batch of vectors to feed into a model.

In [35]:
# create a matrix with Numpy
A = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
])

In [39]:
print(A)

[[1. 2. 3.]
 [4. 5. 6.]]


In [40]:
print(A.shape)

(2, 3)


In [41]:
print(A.ndim)

2


In [42]:
print(A.dtype)

float64


**Operations on matrices:**

- Transpose of a matrix
- Indexing or slicing
- Matrix multiplication

In [43]:
A = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
])

In [44]:
# create a matrix with Numpy
B = np.array([
    [1.4, 1.6, 3.7],
    [4.5, -5.1, 2.2],
])

In [45]:
# compute the transpose
A.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [47]:
np.transpose(A)

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [50]:
print(A.shape)
print(B.shape)

(2, 3)
(2, 3)


In [54]:
# Matrix multiply
A @ B.T

array([[15.7,  0.9],
       [35.8,  5.7]])

**Indexing or slicing:**

$A[i]$ gives the row i-th, $A[:, j]$ gives the column j-th; $A[i,j]$ gives the element at the position (i, j).

In [55]:
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
A[0]

array([1., 2., 3.])

In [57]:
A[1]

array([4., 5., 6.])

In [58]:
# 1st col
A[:,0]

array([1., 4.])

In [59]:
# if we want to get value 5, then
A[1,1]

np.float64(5.0)