# Linear Algebra with Numpy (Python)

In [2]:
from sympy.polys.subresultants_qq_zz import res
from tornado.autoreload import start
# install numpy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

## Vectors

- Vector is a list of numbers or 1-D array in Numpy.
- Use vectors to represent: a feature column of a dataset; the gradient to descend the loss function

In [4]:
# create vectors in Numpy
x = np.array([0.5, 1.2, 3.5, 7.3])

In [5]:
print(x)

[0.5 1.2 3.5 7.3]


**Notice:** `x` is a object in Numpy.

In [6]:
# check the type of the vector
print(type(x))

<class 'numpy.ndarray'>


For any `Numpy` array, we have some properties: `x.shape` (shape of the array) or `x.ndim` (dimensions) and `x.dtype` (data type)

In [7]:
print(x.shape)

(4,)


In [8]:
print(x.ndim)

1


In [9]:
print(x.dtype)

float64


In [10]:
x = np.array([0.5, 1.2, 3.5, 7.3])
y = np.array([0.2, 1.4, 2.2, 2.1])

In [11]:
len(x) == len(y)

True

In [12]:
# linear combination of vectors
z = 2*x + 3*y
print(z)

[ 1.6  6.6 13.6 20.9]


**Elementwise product:**

If $x = (x_1,x_2,\ldots,x_n)$ and $y = (y_1,y_2,\ldots,y_n)$ then
$$
x*y = (x_1y_1, x_2y_2, \ldots, x_ny_n).
$$

In [13]:
# what is x * y?
print(x*y)

[ 0.1   1.68  7.7  15.33]


**Dot Product:**
If $x = (x_1,x_2,\ldots,x_n)$ and $y = (y_1,y_2,\ldots,y_n)$ then
$$
x \dot y = x_1y_1 + x_2y_2+\cdots+x_ny_n.
$$

In [14]:
# compute the dot product
np.dot(x,y) == np.sum(x*y)

np.True_

In [15]:
x @ y

np.float64(24.810000000000002)

## Norm (len) of vectors
A norm of a vector is defined as
$$
\|x\|_{p} = (|x_1|^p+|x_2|^p+\cdots+|x_n|^p)^{1/p}
$$
In Numpy, we only need for $p=1$, $p=2$ or $p=\infty$

In [16]:
# compute the norm of vector
v = np.array([3.0, -4.0, 0])

In [17]:
l1_norm = np.linalg.norm(v, 1)
print(l1_norm)

7.0


In [18]:
linf_norm = np.linalg.norm(v, np.inf)
print(linf_norm)

4.0


In [19]:
# 12 norm
l2_norm = np.linalg.norm(v, 2)
print(l2_norm)

5.0


In [20]:
l2_norm = np.linalg.norm(v)
print(l2_norm)

5.0


**Example:** Write a function to compute the cosine similarity of two vectors.
If $x = (x_1,\ldots,x_n)$ and $y = (y_1,\ldots,y_n)$ then
$$
\cos(\theta) = \frac{x\cdot y}{\|x\|\|y\|}.
$$

In [21]:
def cos_sim(x, y):
    return (x @ y) / (np.linalg.norm(x) * np.linalg.norm(y))

In [22]:
# make up vectors
cat = np.array([0.9, 0.1, 0.0])
dog = np.array([0.85, 0.2, 0.0])
car = np.array([0.0, 0.1, 0.9])

In [23]:
# check the similarity between cat and dog
cos_sim(cat, dog)

np.float64(0.9927566538132715)

In [24]:
cos_sim(cat, car)

np.float64(0.012195121951219513)

## Matrices

Matrix is just a 2-D array in Numpy (or a list of lists). Use matrices for
- dataset (rows and columns)
- weight of layers in a DL model
- a batch of vectors to feed into a model.

In [25]:
# create a matrix with Numpy
A = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
])

In [26]:
print(A)

[[1. 2. 3.]
 [4. 5. 6.]]


In [27]:
print(A.shape)

(2, 3)


In [28]:
print(A.ndim)

2


In [29]:
print(A.dtype)

float64


**Operations on matrices:**

- Transpose of a matrix
- Indexing or slicing
- Matrix multiplication

In [30]:
A = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
])

In [31]:
# create a matrix with Numpy
B = np.array([
    [1.4, 1.6, 3.7],
    [4.5, -5.1, 2.2],
])

In [32]:
# compute the transpose
A.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [33]:
np.transpose(A)

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [34]:
print(A.shape)
print(B.shape)

(2, 3)
(2, 3)


In [35]:
# Matrix multiply
A @ B.T

array([[15.7,  0.9],
       [35.8,  5.7]])

**Indexing or slicing:**

$A[i]$ gives the row i-th, $A[:, j]$ gives the column j-th; $A[i,j]$ gives the element at the position (i, j).

In [36]:
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [37]:
A[0]

array([1., 2., 3.])

In [38]:
A[1]

array([4., 5., 6.])

In [39]:
# 1st col
A[:,0]

array([1., 4.])

In [40]:
# if we want to get value 5, then
A[1,1]

np.float64(5.0)

## Rank and determinate of matrices

In [41]:
A = np.array([
    [1.1, 2.1, 2.5],
    [2.2, 3.1, -1.1],
    [0.5, 0.1, -0.3]
])

In [42]:
rank = np.linalg.matrix_rank(A)

In [43]:
print(rank)

3


In [44]:
# compute the determinant
det = np.linalg.det(A)
print(det)

-3.9959999999999996


In [45]:
A_inv = np.linalg.inv(A)

In [46]:
print(A_inv)

[[ 0.20520521 -0.22022022  2.51751752]
 [-0.02752753  0.3953954  -1.67917918]
 [ 0.33283283 -0.23523524  0.3028028 ]]


In [47]:
A @ A_inv

array([[ 1.00000000e+00, -5.55111512e-17,  8.32667268e-17],
       [ 2.03985422e-17,  1.00000000e+00, -1.32365479e-16],
       [ 1.47974170e-17,  1.40417096e-17,  1.00000000e+00]])

In [50]:
# generate an identity matrix
I_3 = np.eye(3)

In [51]:
I_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# Check if A@A_inv == I_3 (identity)
np.allclose(A@A_inv, I_3)

True

## Special vectors and matrices

In [54]:
# zero vectors
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [56]:
# vector with ones
y = np.ones(5)
print(y)

[1. 1. 1. 1. 1.]


In [57]:
# create a vector of type float
a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a)

[1. 2. 3. 4. 5.]


In [59]:
# create a zero vector that has the same len and same dtypes as a
b = np.array([0, 0, 0, 0, 0], dtype=float)
print(b)

[0. 0. 0. 0. 0.]


In [61]:
# list comprehension
b = np.array([0 for i in range(len(a))], dtype=float)
print(b)

[0. 0. 0. 0. 0.]


In [63]:
# use zero function
b = np.zeros(len(a), dtype=float)
print(b)

[0. 0. 0. 0. 0.]


In [64]:
# Pythonic way to do this
b = np.zeros_like(a)
print(b)

[0. 0. 0. 0. 0.]


In [65]:
# create zero matrix
A = np.zeros((3,4)) # (3,4) is the shape
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Randomization in Numpy

**Generate random vectors:**

In [66]:
# generate random integer vector
x = np.random.randint(low=1, high=5, size=5)
print(x)

[3 3 2 2 3]


In [77]:
# gen random float vector
y = np.random.normal(loc=0, scale=1.4, size=6)
print(y)

[ 0.75323698  2.70004407 -1.45710092 -1.73238014 -1.43006201 -0.19310115]


In [88]:
# generate random float vector (uniform distribution)
z = np.random.uniform(low=0, high=3, size=5)
print(z)

[0.6611573  2.03152023 1.25365825 1.15778439 1.34150524]


**Generate random matrices:**

In [95]:
# gen int matrix
A = np.random.randint(low=1, high=5, size=(4,5))
print(A)

[[4 3 1 1 2]
 [1 3 1 4 2]
 [1 2 3 1 2]
 [4 4 4 3 1]]


In [96]:
# gen random float matrix (normal distributin)
B = np.random.normal(loc=1.0, scale=0.5, size=(4,4))
print(B)

[[ 0.43512753  1.15959826  1.42168116  0.85219045]
 [ 1.09804334  0.95987031  0.76726422  1.49285179]
 [ 1.40725817  0.79037109  1.32032801  0.51692192]
 [ 0.72639165 -0.01812206 -0.03686344  0.88992207]]


## Vector-valued function
Suppose we have a function $y=f(x)$ and a vector $v = (v_1,\ldots, v_n)$. We want to define $f(v)$.

$$
f(v) = (f(v_1),\ldots, f(v_1)).
$$

**Example:**
- Generate a random vector, v, (float) of size n = 200
- Use the for loop to determine the sin(v).

In [98]:
# compute sin(v)
import math

In [103]:
n = 5000
# gen random vector (either normal or uniform distribution)
v = np.random.normal(loc=0, scale=1.5, size=n)
print(v.shape)

(5000,)


In [106]:
# use for loop
# write a function to compute sin_v
def sin(v):
    result = []
    n = len(v)
    for i in range(n):
        result.append(math.sin(v[i]))
    sin_v = np.array(result)
    return sin_v

In [107]:
print(sin(v).shape)

(5000,)


**Measure the running time**

In [108]:
import time

In [109]:
# test the computing time for n from 5000 to 10000
for n in range(5_000, 10_000, 100):
    v = np.random.normal(loc=0, scale=1.5, size=n)
    star_time = time.time()
    sin_v = sin(v)
    end_time = time.time()
    print(f"The running time for n={n} is {end_time - star_time}")

The running time for n=5000 is 0.0008819103240966797
The running time for n=5100 is 0.0008282661437988281
The running time for n=5200 is 0.0008189678192138672
The running time for n=5300 is 0.0008602142333984375
The running time for n=5400 is 0.0008449554443359375
The running time for n=5500 is 0.0008490085601806641
The running time for n=5600 is 0.000865936279296875
The running time for n=5700 is 0.0008790493011474609
The running time for n=5800 is 0.0009069442749023438
The running time for n=5900 is 0.0009248256683349609
The running time for n=6000 is 0.0009248256683349609
The running time for n=6100 is 0.0010037422180175781
The running time for n=6200 is 0.0010030269622802734
The running time for n=6300 is 0.0009868144989013672
The running time for n=6400 is 0.000988006591796875
The running time for n=6500 is 0.0009999275207519531
The running time for n=6600 is 0.0010199546813964844
The running time for n=6700 is 0.00102996826171875
The running time for n=6800 is 0.00105714797973632

In [115]:
n = 10_000_000
v = np.random.normal(loc=0, scale=1.5, size=n)
star_time = time.time()
sin_v = sin(v)
end_time = time.time()
print(f"Running Time for: {end_time - star_time}")

Running Time for: 1.6231160163879395
